export const CartActionTypes = {
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',

    PRODUCT_AMOUNT_INCREMENT: 'PRODUCT_AMOUNT_INCREMENT',
    PRODUCT_AMOUNT_DECREMENT: 'PRODUCT_AMOUNT_DECREMENT',
    
    SET_TOTAL_SUM: 'SET_TOTAL_SUM'
    // other constatns
    // ...
}
