export const CART_TYPES = {
    CART_LIST_REQUEST: 'CART_LIST_REQUEST',
    CART_LIST_SUCCESS: 'CART_LIST_SUCCESS',
    CART_LIST_FAIL: 'CART_LIST_FAIL',
    PRODUCT_AMOUNT_INCREMENT: 'PRODUCT_AMOUNT_INCREMENT',
    PRODUCT_AMOUNT_DECREMENT: 'PRODUCT_AMOUNT_DECREMENT'
}